### ISSUE TITLE
appEngine plugin doesn't respect proxy

### ISSUE THREAD

**Issue by gabin8** [GoogleCloudPlatform/gradle-appengine-plugin#115]
Hi. I have proxy settings in Gradle VM options: 
-Dhttp.proxyHost=192.168.100.1 -Dhttp.proxyPort=8080
When I try to build endpoint I get this error

> Execution failed for task ':api:appengineEndpointsGetClientLibs'.
> There was an error running endpoints command get-client-lib: connect timed out

But the internet is available for other tasks. Why can't I use proxy?

**Comment by sachithkn** [comment]
@gabin8 i have this error ,Can you explain what you have done?Thanks in advance.
