### ISSUE TITLE
Development server still running after failed appengineFunctionTest execution while inside Android Studio

### ISSUE THREAD

**Issue by foens** [GoogleCloudPlatform/gradle-appengine-plugin#145]
I have a lot of tests that run against the development server using the task `appengineFunctionTest`. However, it seems that the server is not terminated when a test fails while running `appengineFunctionTest` inside Android Studio. This is rather annoying, since the next execution of `appengineFunctionTest` will then fail, only because it cannot clear the exploded-war folders.

If run from gradle, the development server is shut down correctly. This is only an issue while executed from within Android Studio. After failing tests, the local development server is still running on http://localhost:8080/_ah/admin

I am unsure if this should be reported here, or to Android Studio. I hope you are able to fix this problem.

**Comment by loosebazooka** [comment]
I think I figured this one out.  If the task fails in daemon mode, the server doesn't stop until the daemon shuts down.  I'm going to try and finalize the task with a "stop" task and see if that does the equivalent of a "Try/Finally" to unconditionally shut down the server at the end of each run.

**Comment by foens** [comment]
That sounds like a plausible reason. That is at least one of the differences between normal gradle command line and Android Studio, that Studio runs gradle in daemon mode.
