### ISSUE TITLE
Gradle Tooling API cannot build HierarchicalEclipseProject model for a project using appengine plugin 

### ISSUE THREAD

**Issue by yunspace** [GoogleCloudPlatform/gradle-appengine-plugin#160]
Using com.google.appengine:gradle-appengine-plugin:1.9.17 I get the error:

    java.io.File cannot be cast to org.gradle.api.artifacts.Configuration

I raised the following error with the Eclipse and Gradle folks. They've directed me to raise an issue here. All details are available here: http://forums.gradle.org/gradle/topics/gradle-tooling-api-cannot-build-hierarchicaleclipseproject-model-for-a-project-using-appengine-plugin?utm_source=notification&utm_medium=email&utm_campaign=new_reply&utm_content=reply_button&reply%5Bid%5D=15222186#reply_15222186

The code that need to fixed is:
https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/blob/d866b74bc648a56a50909670691b8566cf2a45e3/src/main/groovy/com/google/appengine/AppEnginePlugin.groovy#L672

To change

    plugin.model.classpath.plusConfigurations += functionalTestRuntimeConfiguration

To:

    plugin.model.classpath.plusConfigurations += [functionalTestRuntimeConfiguration]

Please look into this. Many thanks!

**Comment by loosebazooka** [comment]
Great! I'll take a look at this. We don't get much feedback from eclipse users so please report anything you find.

**Comment by loosebazooka** [comment]
I'll put this is, we're always open to pull requests though, so please feel free to send in fixes as PRs in the future!

**Comment by yunspace** [comment]
Thanks!
