### ISSUE TITLE
Classpath issues

### ISSUE THREAD

**Issue by oakstair** [GoogleCloudPlatform/gradle-appengine-plugin#18]
I have made a minimal test project to test this plugin. It builds and deploys but when running the app I get 

    Unresolved compilation problems: 
	The import com.google.appengine.api cannot be resolved
	Queue cannot be resolved to a type
	QueueFactory cannot be resolved
        ...

See https://github.com/oakstair/gradle-gae-plugin-tryout

**Comment by oakstair** [comment]
Yesterday I made a new try with  https://github.com/oakstair/gradle-gae-plugin-tryout

First I got the same problem but then suddenly it started to work. Really frustrating.

I laborated with updating my jdk 1.7 to latest version perhaps I cant see what was change that was fixing the classpath problem when uploading the orders1.xml file.

I have commited my changes to gradle-gae-plugin-tryout

One irritating message is "**Class JavaLaunchHelper is implemented in both ...**"

    € gradle appRun
    :compileJava
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    :processResources UP-TO-DATE
    :classes
    :war
    :appengineExplodeApp
    :appengineRun
    Executing [/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/bin/java, -Xdebug, -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8889, -Xmx1024m, -XX:MaxPermSize=512m, -XstartOnFirstThread, -javaagent:/Users/gunnar/dev/appengine-java-sdk-1.9.19/lib/agent/appengine-agent.jar, -Xbootclasspath/p:/Users/gunnar/dev/appengine-java-sdk-1.9.19/lib/override/appengine-dev-jdk-overrides.jar, -classpath, /Users/gunnar/dev/gradle-2.3/lib/gradle-launcher-2.3.jar:/Users/gunnar/dev/appengine-java-sdk-1.9.19/lib/appengine-tools-api.jar, com.google.appengine.tools.development.DevAppServerMain, --property=kickstart.user.dir=/Users/gunnar/git/gradle-gae-plugin-tryout, --port=8888, --address=localhost, --allow_remote_shutdown, /Users/gunnar/git/gradle-gae-plugin-tryout/build/exploded-app]
    objc[5985]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

But since it work this issue may be closed I guess even do I don't know what fixed the problem.

**Comment by loosebazooka** [comment]
perhaps your answer is here? http://stackoverflow.com/questions/20794751/class-javalaunchhelper-is-implemented-in-both-one-of-the-two-will-be-used-whic
