### ISSUE TITLE
Is this plugin supported by google or is it a private initiative?

### ISSUE THREAD

**Issue by oakstair** [GoogleCloudPlatform/gradle-appengine-plugin#185]
I have a general question about this plugin since (without pissing anyone off) the support sometime is slow. Is google behind this or is it based on voluntary work?

We have a very huge appengine application that is generating loads of money too Google (+us) and we would really love to leave our current eclipse based dev environment (with manually handled dependencies) and step up to Gradle.

I have now and then tried this without success but decided to give it a new try yesterday.

My current problems are 2:

* Eclipse complains about the generated project. See https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/issues/184
*  When running **gradle appengineRun** we get NoClassDefFound. See https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/issues/91

Big thanks in advance for anyone that helps us getting forward in this matter!

**Comment by loosebazooka** [comment]
This is an opensource project that get community and Google contributions.  It is maintained by Google as a part time project.  Our concentration is on command line builds and interactions with Intellij, with most Eclipse issues and contributions coming from the community.

**Comment by oakstair** [comment]
This issue may be closed now!
