### ISSUE TITLE
disableUpdateCheck doesn't seem to work

### ISSUE THREAD

**Issue by bes** [GoogleCloudPlatform/gradle-appengine-plugin#187]
System: Ubuntu Linux 12.04
Launch the backend from Android Studio with default configuration

    ...
    classpath 'com.google.appengine:gradle-appengine-plugin:1.9.19'
    ...
    
    dependencies {
        appengineSdk 'com.google.appengine:appengine-java-sdk:1.9.19'
        ...
    }
    
    appengine {
        disableUpdateCheck = true
        downloadSdk = true
        appcfg {
            oauth2 = true
        }
    }

but the launch command looks like this:

    /usr/lib/jvm/java-1.7.0-openjdk-amd64/bin/java -javaagent:/home/me/sdk/appengine-java-sdk-1.9.19/lib/agent/appengine-agent.jar -Xbootclasspath/p:/home/me/sdk/appengine-java-sdk-1.9.19/lib/override/appengine-dev-jdk-overrides.jar -Didea.launcher.port=7534 -Didea.launcher.bin.path=/home/me/apps/android-studio/bin -Dfile.encoding=UTF-8 -classpath /home/me/sdk/appengine-java-sdk-1.9.19/lib/appengine-tools-api.jar:/home/me/apps/android-studio/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain com.google.appengine.tools.development.DevAppServerMain --address=localhost --port=8080 /home/me/my-project/backend/build/exploded-app

Notice the lack of --disable_update_check!

Since I am behind a proxy, this takes a LOT of time, waiting for the update check to time out.

**Comment by loosebazooka** [comment]
Yeah, this is a bug.  You can manually edit the run configuration for now and include it in.  I've added a bug to the android studio tracker : https://code.google.com/p/android/issues/detail?id=170627&thanks=170627&ts=1430242551

**Comment by bes** [comment]
@loosebazooka I tried finding an option for adding it manually, but VM Args only passes stuff to the java command directly, not to the appengine jar. Where do you suggest I add it?

BR Erik

**Comment by loosebazooka** [comment]
You're right, my fault.  

You can try running the gradle task directly instead of the ide implementation.
Create a new gradle run configuration in the "Edit Configurations..." that calls `:backend:appengineRun`

Another option is running from the command line instead of the ide.

    $ ./gradlew :backend:appengineRun

I understand that isn't ideal, but it might serve you until a fix can be put in.

**Comment by bes** [comment]
Cool, thanks. Currently I just copied that huge command line and added --disable_update_check on there. Running from terminal isn't as nice as doing it from AS though ;)
