### ISSUE TITLE
is SystemServiceServlet in web.xml mandatory?

### ISSUE THREAD

**Issue by zandrade** [GoogleCloudPlatform/gradle-appengine-plugin#192]
My app engine project does not use endpoints, when running gradle build I get the following error:

Execution failed for task ':...:appengineEndpointsGetClientLibs'.
> There was an error running endpoints command get-client-lib: web.xml must have 1 (found:0) SystemServiceServlet servlet

**Comment by loosebazooka** [comment]
No, but it appears your gradle configuration is set up to look for endpoints
    
    appengine {
       endpoints {
            <something>onBuild = true?
       }
    }

do you have a closure like that in your build.gradle?

**Comment by zandrade** [comment]
no, my closure is below

appengine {
    downloadSdk = true;

    warDir = new File("$project.projectDir" + '/build/exploded-war')

    httpPort = 8443
    appcfg {

        if (project.hasProperty("appId")) {
            id = project.appId
        }
    }
}

**Comment by loosebazooka** [comment]
Hrm, do you have an android project somewhere? That perhaps depends on an endpoints configuration?

**Comment by zandrade** [comment]
No android project either, just app an app engine project.

I'm migrating my project from the old gae plugin (https://github.com/bmuschko/gradle-gae-plugin)

**Comment by loosebazooka** [comment]
Any way you'd be willing to share your whole build.gradle?

**Comment by loosebazooka** [comment]
Something is triggering adding that task in when it otherwise wouldn't.

**Comment by zandrade** [comment]
```
apply plugin: 'war'
apply plugin: 'appengine'

configurations {
    all*.exclude group: "org.mortbay.jetty"

    runtime.exclude group: "org.sonatype.sisu.inject", module: "cglib"
    runtime.exclude group: "commons-logging", module: "commons-logging"
    runtime.exclude group: "asm", module: "asm"
    runtime.exclude group: "org.javassist", module: "javassist"

    doclet
    docletExtSrc
}
ext {
        gaeVersion = '1.9.17';
        gaeSharedVersion = '1.9.17-SNAPSHOT'
        googleApiVersion = '1.17.0-rc'
        guavaVersion = '14.0.1';
        guiceVersion = '3.0';
        guiceSharedVersion = '3.0-SNAPSHOT';
        gsonVersion = '2.2.4';
        httpClientVersion = '4.2.2'
        injectVersion = '1';
        jerseyVersion = '1.17.1';
        jerseySharedVersion = '1.17.1-SNAPSHOT';
        jodaTimeVersion = '2.2';
        servletApiVersion = '2.5';
        slf4jVersion = '1.6.6';
        thymeleafVersion = '2.0.16';
        objectifyVersion = '4.1.3'
        apacheCommonsVersion = '3.1'
        entitlementClientVersion = '1.0.+'
        powerMockVersion = '1.5.5'
        junitVersion = '4.11'
        mockitoVersion = '1.9.5'
        joseJwtVersion = '3.8'
    }
buildscript {
    repositories {
        mavenCentral()
    }

dependencies {
        classpath 'com.google.appengine:gradle-appengine-plugin:1.9.21'
    }
}

dependencies {

    appengineSdk 'com.google.appengine:appengine-java-sdk:1.9.17'

    compile project(":My-Libriaries")

    compile "org.slf4j:slf4j-jdk14:1.7.5"
    compile "org.apache.httpcomponents:httpclient:$httpClientVersion"
    compile "org.apache.commons:commons-io:1.3.2"
    compile "commons-lang:commons-lang:2.6"

    runtime("org.reflections:reflections:0.9.8")

    compile "javax.ws.rs:jsr311-api:1.1.1"
    compile "javax.annotation:jsr250-api:1.0"

    compile "com.google.http-client:google-http-client-gson:$googleApiVersion"

    // App Engine SDK
    compile "com.google.appengine:appengine-api-1.0-sdk:$gaeVersion"
    compile "com.google.appengine:appengine-tools-sdk:$gaeVersion"
    compile "com.google.appengine:appengine-api-labs:$gaeVersion"

    compile "com.sun.jersey:jersey-core:$jerseyVersion"
    compile "com.sun.jersey:jersey-client:$jerseyVersion"
    compile "com.sun.jersey:jersey-server:$jerseyVersion"
    compile "com.sun.jersey:jersey-servlet:$jerseyVersion"
    compile "com.sun.jersey.contribs:jersey-guice:$jerseyVersion"

    compile "org.slf4j:jcl-over-slf4j:1.7.5"

    compile "commons-codec:commons-codec:1.8"

    testCompile "junit:junit:$junitVersion"
    testCompile "org.mockito:mockito-core:$mockitoVersion"
    testCompile "org.powermock:powermock-module-junit4:$powerMockVersion"
    testCompile "org.powermock:powermock-api-mockito:$powerMockVersion"
    
    appengineSdk "com.google.appengine:appengine-java-sdk:$gaeVersion"

    compile "com.nimbusds:nimbus-jose-jwt:$joseJwtVersion"

    doclet ("com.carma:swagger-doclet:1.0.3")
}

appengine {
    downloadSdk = true;

    warDir = new File("$project.projectDir" + '/build/exploded-war')
    httpPort = 8443
    appcfg {

        if (project.hasProperty("appId")) {
            id = project.appId
        }
    }
}

task extractDocletExternalSources(type: Copy) {
    configurations.docletExtSrc.resolve().each { from zipTree(it.getAbsolutePath()) }
    into file("${buildDir}/shared-src")
}

task deleteDocletExternalSources(type: Delete) {
    delete file("${buildDir}/shared-src")
}

task generateApiDocs(type: Javadoc, dependsOn: extractDocletExternalSources) {
    source = sourceSets.main.allJava
                .plus(fileTree(buildDir.toString() + '/shared-src').include('**/*.java'))

    classpath = configurations.compile
    destinationDir = reporting.file("rest-api-docs")

    options.classpath = configurations.doclet.files.asType(List)
    options.docletpath = configurations.doclet.files.asType(List)
    options.doclet = "com.carma.swagger.doclet.ServiceDoclet"
   
    options.addStringOption("apiVersion", getArtifactVersion())
    options.addStringOption("docBasePath", "#{docBasePath}")
    options.addStringOption("apiBasePath", "#{apiBasePath}")
    options.addBooleanOption("skipUiFiles", true)
    options.addStringOption("apiAuthorizationsFile", "${project.rootDir}/docs/swagger-jaxrs-doclet/api_auth.json")
    options.addStringOption("apiInfoFile", "${project.rootDir}/docs/swagger-jaxrs-doclet/api_info.json")
    options.addBooleanOption("sortResourcesByPath", true)

    options.addBooleanOption("disableDeprecatedResourceClassExclusion", true)
    options.addBooleanOption("disableDeprecatedModelClassExclusion", true)
    options.addBooleanOption("disableDeprecatedOperationExclusion", true)
    options.addBooleanOption("disableDeprecatedFieldExclusion", true)
    options.addBooleanOption("disableDeprecatedParamExclusion", true)
}

generateApiDocs.doLast {
    tasks.deleteDocletExternalSources.execute()
} 
```

**Comment by loosebazooka** [comment]
Can you post the result of `gradle -m build` ?

**Comment by zandrade** [comment]
```
clean SKIPPED
appengineDownloadSdk SKIPPED
compileJava SKIPPED
processResources SKIPPED
classes SKIPPED
appengineEndpointsGetClientLibs SKIPPED
appengineEndpointsExpandClientLibs SKIPPED
war SKIPPED
appengineExplodeApp SKIPPED
assemble SKIPPED
compileFunctionalTestJava SKIPPED
processFunctionalTestResources SKIPPED
functionalTestClasses SKIPPED
webinflib SKIPPED
appengineRun SKIPPED
appengineFunctionalTest SKIPPED
appengineStop SKIPPED
compileEndpointsSrcJava SKIPPED
processEndpointsSrcResources SKIPPED
endpointsSrcClasses SKIPPED
checkstyleEndpointsSrc SKIPPED
checkstyleFunctionalTest SKIPPED
checkstyleMain SKIPPED
compileTestJava SKIPPED
processTestResources SKIPPED
testClasses SKIPPED
checkstyleTest SKIPPED
test SKIPPED
check SKIPPED
build SKIPPED

```

**Comment by loosebazooka** [comment]
You have no other projects in this? ExpandClientLibs gets called by an endpoints depedency from another project..

Do any of your other build files have a line like 
    
    compile project(module: "<module>", configuration "<endpoints or something>")

**Comment by zandrade** [comment]
I have other compile(project...) that I can't share here
none of those is app engine related

as a side not, I can actually run appengineRun and appengineExplodeApp without issue, is just build that produces the failure

**Comment by loosebazooka** [comment]
Yeah, it looks like whatever project is calling your "compileEndpointsSrcJava" is triggering the client library generation.

Check your settings.gradle for all the projects that are being included. Check all those build files for dependencies on client library generation (especially if they are defining a sourceSet called endpointsSrc).

**Comment by ArseniKavalchuk** [comment]
Check all your project if they set up **getClientLibsOnBuild = true**.
Then set up **getClientLibsOnBuild = false** and **getDiscoveryDocsOnBuild = false** explicitly
```groovy
    appengine {
        httpPort = 8888
        downloadSdk = true
        jvmFlags = ['-Xdebug', '-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000']
        appcfg {
            oauth2 = true
        }
        endpoints {
            getClientLibsOnBuild = false
            getDiscoveryDocsOnBuild = false
        }
    }
```

**Comment by zandrade** [comment]
I have verified that none of the projects calls getClientLibsOnBuild or uses app engine in any way. Using the appengine closure above did  not solve the issue.

**Comment by ArseniKavalchuk** [comment]
Maybe a weird question, but nonetheless. What is exact build command? Is it a batch/shell file or just `gradle clean build`?

**Comment by zandrade** [comment]
correct gradle clean build causes the issue
but in general any call to the build task causes the problem

**Comment by loosebazooka** [comment]
It appears the checkstyle plugin isn't interacting well here.  Checkstyle wants to check the style on all SourceSets. Then EndpointsSrc sourceset is preconfigured for endpoints, but not used otherwise. Checkstyle still wants to check it though.

One option to to ignore that source when using checkstyle.

./gradlew build -x checkEndpointsSrc

You can explicitly configure it too https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CheckstyleExtension.html#org.gradle.api.plugins.quality.CheckstyleExtension:sourceSets

**Comment by zandrade** [comment]
-x checkstyleEndpointsSrc solved the issue

thanks

**Comment by patjackson52** [comment]
I am getting this issue as well.  -x checkstyleEndpointsSrc does not appear to be a task and gradle says it can't find it.  I am using the latest version 1.9.32

I have a Appengine module with endpoints that depends on another app engine module that does not have endpoints.  I get the error when the second module is built as a dependency.  I have tried all of the suggestions with no success.  Currently blocking my project. 

Error:Execution failed for task ':appengine:appengineEndpointsGetClientLibs'.
> There was an error running endpoints command get-client-lib: web.xml must have 1 (found:0) SystemServiceServlet servlet
