### ISSUE TITLE
[Question] How do I view appengine logs when appengineRun is in daemonMode

### ISSUE THREAD

**Issue by keithmarsh** [GoogleCloudPlatform/gradle-appengine-plugin#197]
In eclipse, pre gradle-2,3, when running in no-deamon mode I could see all my appengine log output in the gradle build console.
Now that it defaults to daemon-mode, where do I go to in Eclipse to see my appengine log output interactively?
I know I can force it run in no-daemon mode, but I'd like to know if they're visible in daemon mode.
Thanks

**Comment by loosebazooka** [comment]
I don't know if eclipse is handing this case wrong.  But I think you can view the gradle daemon logs in <home>/.gradle/daemon/<version>/daemon-<something>.out.log

Is this an issue about seeing any output or just the appengine dev app server? If it's not appengine specific, I would try asking the Gradle/Eclipse teams about their integration.

**Comment by keithmarsh** [comment]
Thanks for the info.
