### ISSUE TITLE
Unsupported SDK warning message

### ISSUE THREAD

**Issue by dulimarta** [GoogleCloudPlatform/gradle-appengine-plugin#201]
I have the following settings in my `gradle.build`:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.appengine:gradle-appengine-plugin:1.9.23'
    }
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'appengine'

sourceCompatibility = 1.7
targetCompatibility = 1.7

dependencies {
  appengineSdk 'com.google.appengine:appengine-java-sdk:1.9.25'
  compile 'com.google.appengine:appengine-endpoints:1.9.25'
  compile 'com.google.appengine:appengine-endpoints-deps:1.9.25'
  compile 'javax.servlet:servlet-api:2.5'
  compile 'com.googlecode.objectify:objectify:5.1.1'
  compile 'com.ganyo:gcm-server:1.0.2'
}
```
But when running my application on a local dev server, I received the following warning:

```
The API version in this SDK is no longer supported on the server!
-----------
Latest SDK:
Release: 1.9.25
Timestamp: Tue Jul 07 15:10:33 EDT 2015
API versions: [1]

-----------
Your SDK:
Release: 1.9.25
Timestamp: Thu Jul 23 15:07:39 EDT 2015
API versions: [1.0]

-----------
Please visit https://developers.google.com/appengine/downloads for the latest SDK.
```

The warning message says the latest SDK has an older date (Jul 7) than my installed SDK (Jul 23).

**Comment by loosebazooka** [comment]
Interesting, well the timestamp is probably modified when the sdk id download on to your computer. We might be behind on releases here.  Will work on putting up 1.9.25 soon.

**Comment by loosebazooka** [comment]
Actually this appears like it could be a bug in appengine. I'm checking with them to see what it is

**Comment by husayt** [comment]
We have the same:
```
The API version in this SDK is no longer supported on the server!
-----------
Latest SDK:
Release: 1.9.25
Timestamp: Tue Jul 07 20:10:33 BST 2015
API versions: [1]

-----------
Your SDK:
Release: 1.9.25
Timestamp: Thu Jul 23 20:07:39 BST 2015
API versions: [1.0]
```

Do you have any updates, on what it is?

**Comment by ankur296** [comment]
I am facing a similar issue..
I want to use the app engine endpoint api for my android app and I added the module through android studio following google guidelines. 

Works well for:
http://1-dot-joketellerapp.appspot.com/?
AND
https://joketellerapp.appspot.com/

Also, the API explorer reflects accurate API details (tested with the param and works fine).. But when I run my android app on a real device i get the 404 error. It doesn't works on the emulator as well!

Note: when I build my server module, I do get this warning:
**************************************
The API version in this SDK is no longer supported on the server!
-----------
Latest SDK:
Release: 1.9.25
Timestamp: Wed Jul 08 00:40:33 IST 2015
API versions: [1]

-----------
Your SDK:
Release: 1.9.25
Timestamp: Fri Jul 24 00:37:39 IST 2015
API versions: [1.0]
**************************************

To counter this I even downloaded the latest available sdk from https://cloud.google.com/appengine/downloads
but to no avail! 

Other info:
Android Studio version = 1.2.2
gradle config:
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.google.appengine:gradle-appengine-plugin:1.9.18'
    }
}

repositories {
    jcenter();
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'appengine'

sourceCompatibility = JavaVersion.VERSION_1_7
targetCompatibility = JavaVersion.VERSION_1_7

dependencies {
    appengineSdk 'com.google.appengine:appengine-java-sdk:1.9.25'
    compile 'com.google.appengine:appengine-endpoints-deps:1.9.25'
    compile 'com.google.appengine:appengine-endpoints:1.9.25'
    compile 'javax.servlet:servlet-api:2.5'
    compile project(':javaJokes')
}

appengine {
    downloadSdk = true
    appcfg {
        oauth2 = true
    }
    endpoints {
        getClientLibsOnBuild = true
        getDiscoveryDocsOnBuild = true
    }
}

**Comment by bpossolo** [comment]
I'm experiencing this too
```
The API version in this SDK is no longer supported on the server!
-----------
Latest SDK:
Release: 1.9.25
Timestamp: Tue Jul 07 12:10:33 PDT 2015
API versions: [1]

-----------
Your SDK:
Release: 1.9.25
Timestamp: Thu Jul 23 12:07:39 PDT 2015
API versions: [1.0]
```

**Comment by loosebazooka** [comment]
Looks like this is a harmless warning : bug tracking at https://code.google.com/p/googleappengine/issues/detail?id=12307

**Comment by Shajeel-Afzal** [comment]
I was able to resolve this problem by adding noCookies = true in appcfg in build.gradle file 

'appengine {
    downloadSdk = true
    appcfg {
        oauth2 = true
        noCookies = true
        email = "EMAIL_ADDRESS"
    }
    endpoints {
        getClientLibsOnBuild = true
        getDiscoveryDocsOnBuild = true
    }
}'

**Comment by aventadorm** [comment]
<img width="860" alt="screen shot 2015-09-13 at 7 54 09 pm" src="https://cloud.githubusercontent.com/assets/11070806/9837088/4318d2b2-5a51-11e5-9e10-977db91002ac.png">

**Comment by jking31cs** [comment]
I have a similar issue happening on 1.9.27:

The API version in this SDK is no longer supported on the server!
-----------
Latest SDK:
Release: 1.9.27
Timestamp: Tue Aug 18 14:28:24 EDT 2015
API versions: [1]

-----------
Your SDK:
Release: 1.9.27
Timestamp: Wed Sep 02 16:29:33 EDT 2015
API versions: [1.0]

**Comment by georgep888** [comment]
A variant of https://b.corp.google.com/u/0/issues/22450096.

thanks,
-georgep

**Comment by mraiyani** [comment]
I have a similar issue happening on 1.9.27:

The API version in this SDK is no longer supported on the server!

Latest SDK:
Release: 1.9.27
Timestamp: Tue Aug 18 14:28:24 EDT 2015
API versions: [1]

Your SDK:
Release: 1.9.27
Timestamp: Wed Sep 02 16:29:33 EDT 2015
API versions: [1.0]

**Comment by zho** [comment]
use this http://mvnrepository.com/artifact/com.google.appengine/appengine-api-stubs/1.9.27

**Comment by loosebazooka** [comment]
It appears this has been fixed in the newer versions of the appengine SDK
