### ISSUE TITLE
Link to geb functional test is incorrect

### ISSUE THREAD

**Issue by keithmarsh** [GoogleCloudPlatform/gradle-appengine-plugin#207]
Link to 
http://blog.proxerd.pl/article/funcational-testing-of-appengine-lyk-applications-with-geb
looks to have changed to 
http://blog.proxerd.pl/article/funcational-testing-of-gae-lyk-applications-with-geb

in your text "Please refer to this short and sweet tutorial for a quickstart."

**Comment by loosebazooka** [comment]
thanks.
