### ISSUE TITLE
appengineUpdate task uploading 0 files to appengine

### ISSUE THREAD

**Issue by kalyansriram** [GoogleCloudPlatform/gradle-appengine-plugin#215]
When i try to deploy a application to appengine its not uploading the changed files to appengine but when i run it in local its building properly. below is the log :

Kalyans-MacBook-Air:MovieAddictV2 Kalyan$ ./gradlew :backend_site:appengineUpdate --debug --info
Starting Build
Settings evaluated using settings file '/Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/settings.gradle'.
Projects loaded. Root project using build file '/Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/build.gradle'.
Included projects: [root project 'MovieAddictV2', project ':app', project ':backend', project ':backend_site', project ':common']
Evaluating root project 'MovieAddictV2' using build file '/Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/build.gradle'.
Evaluating project ':app' using build file '/Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/app/build.gradle'.
Creating configuration compile.
Creating configuration apk.
Creating configuration provided.
Creating configuration wearApp.
Creating configuration androidTestCompile.
Creating configuration androidTestApk.
Creating configuration androidTestProvided.
Creating configuration androidTestWearApp.
Creating configuration testCompile.
Creating configuration testApk.
Creating configuration testProvided.
Creating configuration testWearApp.
Creating configuration debugCompile.
Creating configuration debugApk.
Creating configuration debugProvided.
Creating configuration debugWearApp.
Creating configuration testDebugCompile.
Creating configuration testDebugApk.
Creating configuration testDebugProvided.
Creating configuration testDebugWearApp.
Creating configuration releaseCompile.
Creating configuration releaseApk.
Creating configuration releaseProvided.
Creating configuration releaseWearApp.
Creating configuration testReleaseCompile.
Creating configuration testReleaseApk.
Creating configuration testReleaseProvided.
Creating configuration testReleaseWearApp.
Evaluating project ':common' using build file '/Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/common/build.gradle'.
file or directory '/Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/common/libs', not found
file or directory '/Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/common/libs', not found
file or directory '/Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/common/libs', not found
file or directory '/Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/common/libs', not found
Evaluating project ':backend' using build file '/Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/backend/build.gradle'.
Evaluating project ':backend_site' using build file '/Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/backend_site/build.gradle'.
All projects evaluated.
Selected primary task ':backend_site:appengineUpdate' from project :backend_site
Tasks to be executed: [task ':backend_site:appengineDownloadSdk', task ':backend_site:compileJava', task ':backend_site:processResources', task ':backend_site:classes', task ':backend_site:appengineEndpointsGetClientLibs', task ':backend_site:appengineEndpointsGetDiscoveryDocs', task ':backend_site:war', task ':backend_site:appengineExplodeApp', task ':backend_site:appengineUpdate']
:backend_site:appengineDownloadSdk (Thread[main,5,main]) started.
:backend_site:appengineDownloadSdk
Executing task ':backend_site:appengineDownloadSdk' (up-to-date check took 0.002 secs) due to:
  Task has not declared any outputs.
:backend_site:appengineDownloadSdk (Thread[main,5,main]) completed. Took 0.1 secs.
:backend_site:compileJava (Thread[main,5,main]) started.
:backend_site:compileJava
Skipping task ':backend_site:compileJava' as it is up-to-date (took 0.104 secs).
:backend_site:compileJava UP-TO-DATE
:backend_site:compileJava (Thread[main,5,main]) completed. Took 0.114 secs.
:backend_site:processResources (Thread[main,5,main]) started.
:backend_site:processResources
Skipping task ':backend_site:processResources' as it has no source files.
:backend_site:processResources UP-TO-DATE
:backend_site:processResources (Thread[main,5,main]) completed. Took 0.004 secs.
:backend_site:classes (Thread[main,5,main]) started.
:backend_site:classes
Skipping task ':backend_site:classes' as it has no actions.
:backend_site:classes UP-TO-DATE
:backend_site:classes (Thread[main,5,main]) completed. Took 0.008 secs.
:backend_site:appengineEndpointsGetClientLibs (Thread[main,5,main]) started.
:backend_site:appengineEndpointsGetClientLibs
Skipping task ':backend_site:appengineEndpointsGetClientLibs' as it is up-to-date (took 0.088 secs).
:backend_site:appengineEndpointsGetClientLibs UP-TO-DATE
:backend_site:appengineEndpointsGetClientLibs (Thread[main,5,main]) completed. Took 0.094 secs.
:backend_site:appengineEndpointsGetDiscoveryDocs (Thread[main,5,main]) started.
:backend_site:appengineEndpointsGetDiscoveryDocs
Skipping task ':backend_site:appengineEndpointsGetDiscoveryDocs' as it is up-to-date (took 0.055 secs).
:backend_site:appengineEndpointsGetDiscoveryDocs UP-TO-DATE
:backend_site:appengineEndpointsGetDiscoveryDocs (Thread[main,5,main]) completed. Took 0.061 secs.
:backend_site:war (Thread[main,5,main]) started.
:backend_site:war
Skipping task ':backend_site:war' as it is up-to-date (took 0.063 secs).
:backend_site:war UP-TO-DATE
:backend_site:war (Thread[main,5,main]) completed. Took 0.098 secs.
:backend_site:appengineExplodeApp (Thread[main,5,main]) started.
:backend_site:appengineExplodeApp
Skipping task ':backend_site:appengineExplodeApp' as it is up-to-date (took 0.054 secs).
:backend_site:appengineExplodeApp UP-TO-DATE
:backend_site:appengineExplodeApp (Thread[main,5,main]) completed. Took 0.058 secs.
:backend_site:appengineUpdate (Thread[main,5,main]) started.
:backend_site:appengineUpdate
Executing task ':backend_site:appengineUpdate' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
App Engine SDK root = /Users/Kalyan/.gradle/appengine-sdk/appengine-java-sdk-1.9.20
Java classpath = /Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/gradle/wrapper/gradle-wrapper.jar:/Users/Kalyan/.gradle/appengine-sdk/appengine-java-sdk-1.9.20/lib/appengine-tools-api.jar
Webapp source directory = /Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/backend_site/src/main/webapp
Starting update process...
Using params = [--email=kalyanthedeveloper@gmail.com, --no_cookies, --oauth2, --enable_jar_splitting, --use_java7, update, /Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/backend_site/build/exploded-app]
> Building 88% > :backend_site:appengineUpdate4/V9R8_lE1hnByeFDgAH07uotiAAOwqqIWC68TpkH_kuw
Please enter code: Reading application configuration data...
Oct 30, 2015 1:46:10 AM com.google.apphosting.utils.config.AppEngineWebXmlReader readAppEngineWebXml
INFO: Successfully processed /Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/backend_site/build/exploded-app/WEB-INF/appengine-web.xml
Oct 30, 2015 1:46:10 AM com.google.apphosting.utils.config.AbstractConfigXmlReader readConfigXml
INFO: Successfully processed /Users/Kalyan/Documents/Projects/Movie Addict/Code/Android/MovieAddictV2/backend_site/build/exploded-app/WEB-INF/web.xml

Beginning interaction for module default...
0% Created staging directory at: '/var/folders/f3/_18nbxl15msf8w_695bhmy1m0000gn/T/appcfg3540146447198638346.tmp'
5% Scanning for jsp files.
20% Scanning files on local disk.
25% Scanned 250 files.
28% Initiating update.
31% Cloning 164 static files.
33% Cloning 175 application files.
40% Uploading 0 files.
52% Initializing precompilation...
90% Deploying new version.
95% Will check again in 1 seconds.
98% Will check again in 2 seconds.
99% Will check again in 4 seconds.
99% Closing update: new version is ready to start serving.
99% Uploading index definitions.

Update for module default completed successfully.
Success.
Cleaning up temporary files for module default...
Finished updating process.
:backend_site:appengineUpdate (Thread[main,5,main]) completed. Took 1 mins 4.673 secs.

BUILD SUCCESSFUL

**Comment by loosebazooka** [comment]
I seem to have missed this? Any updates here? Did you figure out the problem?
