### ISSUE TITLE
set default version task needed

### ISSUE THREAD

**Issue by scottmboring** [GoogleCloudPlatform/gradle-appengine-plugin#228]
The mvn tool offers the ability to set the default version

    mvn appengine:set_default_version

This is particularly useful as part of an update like 

    mvn appengine:update_cron appengine:update_indexes appengine:update appengine:set_default_version

Gradle should have a corresponding task

    gradle appengineSetDefaultVersion

**Comment by loosebazooka** [comment]
Sounds like a good idea. Open to pull requests at the moment, or I'll get to in the future.
