### ISSUE TITLE
Question:Different daemon setting for functional test

### ISSUE THREAD

**Issue by keithmarsh** [GoogleCloudPlatform/gradle-appengine-plugin#238]
I like to run daemon = false for appenginerun in eclipse so I see the output in the console.

Is there a way in my build.gradle to have a different daemon  setting when functional testing?

**Comment by loosebazooka** [comment]
hrm... any task configured after appengineRun wont run, because it will block. I think your only option is to run the appserver on your own and run `gradle appengineFuntionalTest -x appengineRun` to exclude it from the normal task execution chain.

**Comment by keithmarsh** [comment]
I'm finding developing appengine with gradle in eclipse a difficult experience.  

- If I set daemon true, I can't see any console output.  If I set it to false, and forget and commit, it breaks all my functional tests (and sometimes jenkins).
- Every time I modify a file (java or static) I have to appenginestop and appenginerun, whereas with Run As Server or Google plugin, it publishes automatically.

Am I missing some crucial step, or is this fundamentally not going to work for me?  

How do other users use gradle-appengine-plugin with eclipse?

**Comment by loosebazooka** [comment]
I don't fully understand what your first issue is, but you should be able to run the dev appserver task before running functional tests.  You can even add a conditional in your functional test task that disables running the devserver to not interfere with your manually started server.  I don't really use eclipse so I don't know how you're launching things, but could you potential make a custom configuration that calls gradle appengineStart first and then gradle appengineFunctionalTest?

For your second problem - you can see this discussion here for hot-code replace: https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/issues/97 The original architecture of this plugin

**Comment by keithmarsh** [comment]
My problem was that I was importing my work into eclipse using BuildShip, which wasn't setting the Dynamic Web Module facet.  I deleted my project, ran gradle eclipse, which also runs elipse-wtp and imported this as a vanilla project, not a gradle project.  Downside is I can't run gradle tasks from eclipse, and have to rebuild project if dependencies change, upside is that I can run project using GAE server, see the console and get republished whenever source changes.  Not ideal, but much better.

Sorry loose, this wasn't really an appengine issue, more an eclipsewtp/buildship issue.  Thanks for listening to my woes.  

Your work on this plugin is appreciated.

**Comment by loosebazooka** [comment]
Heh, I'm still not clear I understood your problem, but I'm glad you figured it out. Please feel free to close this if there is no need for further discussion.

**Comment by keithmarsh** [comment]
https://discuss.gradle.org/t/no-facets-in-project-created-with-1-0-10/15354
