### ISSUE TITLE
Use `gcloud app` instead of `gcloud preview app`

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/gradle-appengine-plugin#249]
https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/blob/a68b880dee6229ed777147fe7e486ac9efa2d7d5/src/main/groovy/com/google/gcloud/task/app/DeployTask.groovy#L28

**Comment by loosebazooka** [comment]
No one should be using this. Is someone using this? This was pretty experimental.

**Comment by tmatsuo** [comment]
It doesn't matter whether or not someone is using this. It's a public repo and it has a reference to `gcloud preview app` which will go away soon :)

**Comment by kamronbatman** [comment]
tmatsuo, can you make a pull request?

**Comment by loosebazooka** [comment]
@kamronbatman are you using this? Once again, no one should be using this. I'm probably going to remove it from the next version to prevent any confusion.

**Comment by kamronbatman** [comment]
Please remove it! 👍
