### ISSUE TITLE
spring 4 with local development server

### ISSUE THREAD

**Issue by tsuncp** [GoogleCloudPlatform/gradle-appengine-plugin#271]
```
@RestController
@RequestMapping(value = "/test")
public class MainController {

    @RequestMapping(value = "/test", method = RequestMethod.GET)
    public String test() {
        return "success";
    }

    @RequestMapping(value = "/test2", method = RequestMethod.GET)
    public String test2() {
        return "success";
    }

}
```

if two method or more is defined in controller, server cannot started .. bad runtime process port  , if there is only one method, no problem..

only exists in local development server, if deploy to app engine , it will work

dependencies : 

compile 'javax.servlet:servlet-api:+'
compile 'com.google.appengine:appengine:+'
compile 'org.springframework:spring-core:+'
compile 'org.springframework:spring-webmvc:+'
compile 'com.google.firebase:firebase-admin:+'

tried using gretty as the local web server , it works

**Comment by patflynn** [comment]
Is this to App Engine Standard?  Are you not using any of the emulated services that the dev appserver provides?

**Comment by tsuncp** [comment]
i found the solution.. 

i follow the different version before from this ... 
https://cloud.google.com/appengine/docs/java/tools/gradle 

I now change to spring boot and the plugin here , it works now .. thanks
