### ISSUE TITLE
appengineRun in background

### ISSUE THREAD

**Issue by sh4d0000** [GoogleCloudPlatform/gradle-appengine-plugin#275]
I couldn't find the daemon option in the docs to run the appengine local dev server in background . Do you plan to support this feature?

**Comment by loosebazooka** [comment]
It's in the README (under convention properties) or just search the page for `daemon`


`daemon`: Specifies whether the local development server should run in the background. When true, this task completes as soon as the server has started. When false, this task blocks until the local development server is stopped (defaults to false).
- Running the App Engine local development server in daemon mode requires that Gradle is also run as a daemon. The local development server will always be stopped when Gradle exits.

**Comment by loosebazooka** [comment]
or are you asking about the new plugin : https://github.com/GoogleCloudPlatform/app-gradle-plugin ?

**Comment by sh4d0000** [comment]
yes the new plugin. I have actually found out there is now appengineStart to do this. thanks
