### ISSUE TITLE
exclude jars

### ISSUE THREAD

**Issue by wmacgyver** [GoogleCloudPlatform/gradle-appengine-plugin#277]
Is it possible to exclude specific jars from being deployed to app engine?

**Comment by loosebazooka** [comment]
Can you elaborate?

**Comment by wmacgyver** [comment]
@loosebazooka there have been times that I use framework that pulls in jetty embedded server. so the final deploy to GAE I end up with  WEB-INF/lib/jetty-http-9.3.6.v20151106.jar etc etc

which is of course not useful on GAE. I can exclude them in the dep block.

but I wasn't sure if there is another way

**Comment by loosebazooka** [comment]
If you don't need it at any point during your development, I would probably just put it in the exclude of the dependency. 

There are some standard gradle exclusion techniques when generating the war which don't put the jar in the war/lib directory as see in this question : http://stackoverflow.com/questions/20707543/gradle-how-to-exclude-jar-from-a-war

But there's no appengine deployment specific exclusion mechanisms.

**Comment by wmacgyver** [comment]
oh, I didn't realize the plugin extends the war task. yea, I can just exclude it using war task way.

thank you!

**Comment by loosebazooka** [comment]
okay, I'm going to close this issue

**Comment by wmacgyver** [comment]
@loosebazooka thank you very much for your help. I just tried it using war exclude, was able to verify in both build/exploded-app/WEB-INF/lib/

and also the final deployed appengine artifact that the exclusion worked
