### ISSUE TITLE
README.md - incorrect endpoints parameters

### ISSUE THREAD

**Issue by opus1269** [GoogleCloudPlatform/gradle-appengine-plugin#279]
In the endpoints closure, the params:

* `clientLibsJarOut`: Output directory of client library jars when exporting. (Must be of type: File, will be created if doesn't exist)
* `clientLibsSrcJarOut`: Output directory of client library source jars when exporting, if not specified no source jars will be copied. (Must be of type: File, will be created if doesn't exist)

should be (no 's' on Lib):

* `clientLibJarOut`: Output directory of client library jars when exporting. (Must be of type: File, will be created if doesn't exist)
* `clientLibSrcJarOut`: Output directory of client library source jars when exporting, if not specified no source jars will be copied. (Must be of type: File, will be created if doesn't exist)

**Comment by loosebazooka** [comment]
Thanks for catching this.
