### ISSUE TITLE
 Connection timed out

### ISSUE THREAD

**Issue by clayclayclay** [GoogleCloudPlatform/gradle-appengine-plugin#285]
Hello,all.
When I try to invoke: `mvn appengine:update` ,I encountered a problem:
```
INFO: Unable to access https://appengine.google.com/api/updatecheck?runtime=java&release=1.9.53&timestamp=1494285082&api_versions=['1.0']
java.net.ConnectException: Connection timed out: connect
```
Could anyone give me some ideas?

**Comment by patflynn** [comment]
could be a transient issue with the update checking service.

Did you try setting `disableUpdateCheck` to true?

**Comment by loosebazooka** [comment]
@ludoch
