### ISSUE TITLE
Failed to apply plugin for gradle 5.0

### ISSUE THREAD

**Issue by shindemanoj** [GoogleCloudPlatform/gradle-appengine-plugin#308]
I am using Gradle 5.0 in the application. When I am trying to build the application I am getting following error:

>FAILURE: Build failed with an exception.
>
>* Where:
>Build file '/home/user/project/build.gradle' line: 19
>
>* What went wrong:
>A problem occurred evaluating project ':project'.
> Failed to apply plugin [id 'appengine']
   > Could not get unknown property 'classesDir' for functional test classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.
>
>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>
>* Get more help at https://help.gradle.org
>
>CONFIGURE FAILED in 0s
>ERROR: Could not get unknown property 'classesDir' for functional test classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

It's working for Gradle 4.10.2
Is it a bug in appengine plugin?

Thanks

**Comment by loosebazooka** [comment]
What version of the appengine-gradle-plugin are you using? I thought we had fixed this.

**Comment by shindemanoj** [comment]
Hello,

Thank you for the response. I am using 1.9.42 version of gradle-appengine-plugin. I tried with 1.9.59 version also. Still no luck.

**Comment by loosebazooka** [comment]
Oh I didn't realize this is the old repository. Please take a look at the [README](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/blob/master/README.md). This project is deprecated and we recommend using the newer plugin.

**Comment by shindemanoj** [comment]
Oh. Thank you.
