### ISSUE TITLE
Appengine plugin build error for gradle:3.4.0

### ISSUE THREAD

**Issue by sevvalboylu** [GoogleCloudPlatform/gradle-appengine-plugin#309]
Could not get unknown property 'classesDir' for functional test classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

My gradle file:
// If you would like more information on the gradle-appengine-plugin please refer to the github page
// https://github.com/GoogleCloudPlatform/gradle-appengine-plugin

buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath 'com.google.appengine:gradle-appengine-plugin:1.9.59'
        classpath 'com.google.cloud.tools:endpoints-framework-gradle-plugin:1.0.2'
        classpath 'com.google.guava:guava:19.0'
    }
}

repositories {
    jcenter()
}

apply plugin: 'java'
apply plugin: 'war'

apply plugin: 'appengine'

sourceCompatibility = JavaVersion.VERSION_1_7
targetCompatibility = JavaVersion.VERSION_1_7

/*
endpointsServer {
    // Endpoints Framework Plugin server-side configuration
    hostname = "${'smart-scheduler-1548361925633'}.appspot.com"
}
*/

dependencies {
    appengineSdk 'com.google.appengine:appengine-java-sdk:+'
    compile 'com.google.appengine:appengine-endpoints:+'
    compile 'com.google.appengine:appengine-endpoints-deps:+'
    compile 'com.google.endpoints:endpoints-framework:2.0.9'
    compile 'com.google.appengine:appengine-api-1.0-sdk:+'
    compile 'javax.inject:javax.inject:1'
    compileOnly 'javax.servlet:javax.servlet-api:3.1.0'
    implementation 'com.yandex.android:mapkit:3.3.1'
    implementation 'com.yandex.android:search:3.3.1'
    implementation 'com.yandex.android:directions:3.3.1'
    implementation 'com.yandex.android:transport:3.3.1'
    implementation 'com.yandex.android:places:3.3.1'
    implementation 'com.google.api-client:google-api-client:1.23.0'

    appengine.run.port = 8080
}

appengine {
    downloadSdk = true
    appcfg {
        oauth2 = true
    }
    endpoints {
        googleClientVersion = '1.23.0'
        getClientLibsOnBuild = true
        getDiscoveryDocsOnBuild = true
    }
}

The line where I am trying to apply appengine plugin, the error for classesDir is given. I searched trough the issues and people mention classesDir being changed to classesDirs, but this means nothing to me since I have nothing related to that.

We read [this](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/issues/308) issue but couldn't find anything helpful in README.
Thank you in advance.

**Comment by loosebazooka** [comment]
The very top of the readme says that this plugin is deprecated and links to a migration guide. We are only making improvements on the new plugin: https://github.com/GoogleCloudPlatform/app-gradle-plugin.
